<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaParchar.Domain\PaParchar.Domain.csproj" />
    <ProjectReference Include="..\PaParchar.Utils\PaParchar.Utils.csproj" />
  </ItemGroup>

</Project>
