// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaParchar.Infrastructure.Configuration.Contexts;

#nullable disable

namespace PaParchar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaParchar.Domain.Entities.Parche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsPrivado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_privado");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(18, 15)
                        .HasColumnType("numeric(18,15)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(18, 15)
                        .HasColumnType("numeric(18,15)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PortadaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("portada_url");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ubicacion");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("parches");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.ParcheHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("dia");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid>("ParcheId")
                        .HasColumnType("uuid")
                        .HasColumnName("parche_id");

                    b.HasKey("Id");

                    b.HasIndex("ParcheId");

                    b.ToTable("parches_horarios");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.ParcheImagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("ParcheId")
                        .HasColumnType("uuid")
                        .HasColumnName("parche_id");

                    b.HasKey("Id");

                    b.HasIndex("ParcheId");

                    b.ToTable("parche_imagenes");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.ParcheHorario", b =>
                {
                    b.HasOne("PaParchar.Domain.Entities.Parche", "Parche")
                        .WithMany("Horarios")
                        .HasForeignKey("ParcheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parche");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.ParcheImagen", b =>
                {
                    b.HasOne("PaParchar.Domain.Entities.Parche", "Parche")
                        .WithMany("Imagenes")
                        .HasForeignKey("ParcheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parche");
                });

            modelBuilder.Entity("PaParchar.Domain.Entities.Parche", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
